Repository Mohamed-Redouane/SOEN390-Asymptotes, pull requests merged in 2025-02, with the labels that each got.

#43 Google maps API Implementation
  cypress.config.js
  cypress/e2e/MapComponent.cy.js
  cypress/support/component-index.html
  cypress/support/component.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.css
  frontend/src/App.tsx
  frontend/src/MapComponent.tsx
  frontend/tsconfig.app.json
  package-lock.json
  package.json
Labels: enhancement

#54 Feature/Campus-toggle
  .gitignore
  cypress/e2e/BottomNavBar.cy.js
  frontend/.env.example
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.css
  frontend/src/App.tsx
  frontend/src/Components/BottomNavBar.tsx
  frontend/src/Components/MapComponent.tsx
  frontend/src/Components/NavBar.tsx
  frontend/src/assets/image.png
  frontend/src/assets/logo.png
  frontend/src/main.tsx
  frontend/src/pages/LOYCampus.tsx
  frontend/src/pages/SGWCampus.tsx
  frontend/src/setupTests.js
  frontend/src/test/BottomNavBar.test.tsx
  frontend/src/test/routing.test.tsx
  frontend/vite.config.ts
Labels: enhancement

#87 Test/sonar qube ci
  .github/workflows/build.yml
  backend/package.json
  backend/vitest.config.ts
Labels: bug, CI/CD

#93 Refine CI Pipeline & SonarQube Analysis
  .github/workflows/build.yml
  .github/workflows/ci-pipeline.yml
  frontend/.gitignore
  frontend/package-lock.json
  frontend/package.json
  frontend/src/setupTests.ts
  frontend/src/test/BottomNavBar.test.tsx
  frontend/src/test/Components/BottomNavBar.test.tsx
  frontend/src/test/routing.test.tsx
  frontend/src/test/utils/CheckIfUserInBuilding.test.tsx
  frontend/vitest.config.ts
Labels: enhancement, CI/CD

#97 Refactoring and Fixing SonarQube Issues
  .github/workflows/build.yml
  backend/src/app.ts
  backend/src/services/EmailVerificationService.ts
  backend/src/services/authService.ts
  backend/src/tests/middlewares/sessionMiddleware.test.ts
  backend/src/tests/services/emailService.test.ts
  backend/src/tests/services/emailTemplate.test.ts
  backend/src/utils/emailValidation.ts
  frontend/src/Components/Auth/RegisterForm.tsx
  frontend/src/Components/ToggleCampusComponent.tsx
  frontend/src/Components/UserLocation.tsx
  frontend/src/pages/Auth/RequestPasswordResetPage.tsx
  frontend/src/pages/Auth/ResetPasswordPage.tsx
  frontend/src/pages/LOYCampus.tsx
  frontend/src/pages/SGWCampus.tsx
  frontend/src/test/Components/BottomNavBar.test.tsx
  frontend/src/test/utils/authUtils.test.ts
  frontend/src/test/utils/axiosUtils.test.ts
  frontend/src/test/utils/distanceCalculation.test.ts
  frontend/src/utils/authUtils.ts
Labels: refactoring

#104 Feature/direction-request
  .github/workflows/pull_request_template.md
  backend/.env.example
  backend/package-lock.json
  backend/package.json
  backend/src/routes/index.ts
  backend/src/routes/mapRoutes.ts
  backend/src/services/maps_services/directionsService.ts
  backend/src/services/maps_services/placesServices.ts
  backend/src/tests/routes/index.test.ts
  backend/src/tests/routes/mapRoutes.test.ts
  backend/src/tests/services/directionsServices.test.ts
  cypress/e2e/BottomNavBar.cy.js
  cypress/e2e/Directions.cy.js
  frontend/package-lock.json
  frontend/src/Components/DirectionsViewMap.tsx
  frontend/src/api/authApi.ts
  frontend/src/api/index.ts
  frontend/src/api/mapsApi.ts
  frontend/src/pages/Directions.tsx
  frontend/src/pages/DirectionsPage.tsx
  frontend/src/routes.tsx
  frontend/src/services/PlaceServices.ts
  frontend/src/services/directionsServices.ts
  frontend/src/utils/distanceCalculation.ts
  package-lock.json
Labels: documentation, enhancement

#106 Feature/indoor direction
  .vscode/settings.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.css
  frontend/src/Components/BottomNavBar.tsx
  frontend/src/Components/IndoorDirections/AccessibleToggle.tsx
  frontend/src/Components/IndoorDirections/BuildingSelector.tsx
  frontend/src/Components/IndoorDirections/CameraEvents.tsx
  frontend/src/Components/IndoorDirections/ClickNavigation.tsx
  frontend/src/Components/IndoorDirections/FloorSelector.tsx
  frontend/src/Components/IndoorDirections/IndoorPOI.tsx
  frontend/src/Components/IndoorDirections/Labels.tsx
  frontend/src/Components/IndoorDirections/SearchNavigation.tsx
  frontend/src/Components/NavBar.tsx
  frontend/src/pages/IndoorDirections.tsx
  frontend/src/routes.tsx
Labels: enhancement
