Repository Mohamed-Redouane/SOEN390-Asymptotes, pull requests merged in 2025-04, with the labels that each got.

#180 Refactor shuttle components
  frontend/src/components/Shuttle/MapComponent.tsx
  frontend/src/components/Shuttle/MapController.tsx
  frontend/src/components/Shuttle/NextDeparture.tsx
  frontend/src/components/Shuttle/ScheduleItem.tsx
  frontend/src/pages/Shuttle.tsx
  frontend/src/services/shuttle-service.ts
Labels: refactoring

#183 [FIX] correct positioning and styling of message component
  frontend/src/components/UserLocation.tsx
Labels: bug, usability-testing

#184 Fix/usability issues
  cypress/e2e/POIs.cy.js
  frontend/src/components/ModalPOI.tsx
  frontend/src/pages/Campus.tsx
Labels: usability-testing, ui-improvement

#178 "feat(shuttle): implement actual shuttle route display between campus…
  backend/src/routes/mapRoutes.ts
  backend/src/services/maps_services/directionsService.ts
  backend/src/services/maps_services/placesServices.ts
  backend/src/services/maps_services/shuttleRouteService.ts
  backend/src/tests/routes/mapRoutes.test.ts
  backend/src/tests/services/directionsService.test.ts
  backend/src/tests/utils/shuttleRouteService.test.ts
  frontend/src/components/RouteRenderer.tsx
  frontend/src/pages/Directions.tsx
Labels: enhancement

#186 [update] change of default directions page
  cypress/e2e/BottomNavBar.cy.js
  frontend/src/components/BottomNavBar.tsx
Labels: usability-testing, ui-improvement

#187 Fix the bug about additional information of building
  frontend/src/components/MapComponent.tsx
Labels: refactoring, 🐛 Bug Fix

#185 FEATURE - Optional Feature - Smart Planner integration
  cypress/e2e/GoogleCalendarComponents.cy.js.sk
  cypress/e2e/SmartPlanner.cy.js.sk
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/SmartPlanner.tsx
  frontend/src/components/TodaysTaskList.tsx
  frontend/src/pages/CalendarPage.tsx
  frontend/src/test/utils/SmartPlanner.test.tsx
Labels: enhancement

#192 Refactor Pages
  frontend/src/pages/Auth/VerifyEmailPage.tsx
  frontend/src/pages/CalendarPage.tsx
  frontend/src/pages/Campus.tsx
  frontend/src/pages/Directions.tsx
Labels: refactoring

#189 Feature/additional building start
  frontend/src/components/BuildingMarkers.tsx
  frontend/src/pages/Directions.tsx
  frontend/src/test/utils/infoBuilding.test.ts
  frontend/src/utils/infoBuilding.ts
Labels: enhancement

#190 [Refactor] - Use nullish coalescing operator for util files
  frontend/src/utils/authUtils.ts
  frontend/src/utils/infoBuilding.ts
  frontend/src/utils/time-utils.ts
Labels: refactoring

#191 [REFACTOR] Add changes to api services according to SonarQube
  frontend/src/api/authApi.ts
  frontend/src/api/mapsApi.ts
  frontend/src/components/BottomNavBar.tsx
  frontend/src/components/TodaysTaskList.tsx
  frontend/src/test/utils/calendar-utils.test.ts
  package-lock.json
Labels: refactoring

#194 [ADD] Added extra functionality to the smart planner
  frontend/src/components/SmartPlanner.tsx
Labels: enhancement
