Repository Mohamed-Redouane/SOEN390-Asymptotes, pull requests merged in 2025-03, with the labels that each got.

#108 Feature/google calendar integration
  .DS_Store
  cypress/e2e/GoogleCalendarComponents.cy.js
  frontend/.env.example
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Components/CalendarSelector.tsx
  frontend/src/Components/ErrorMessage.tsx
  frontend/src/Components/EventDetailsModal.tsx
  frontend/src/Components/GoogleCalendarConnect.tsx
  frontend/src/Components/WeekView.tsx
  frontend/src/pages/CalendarPage.tsx
  frontend/src/routes.tsx
Labels: enhancement

#110 E2E Test for Mappedin and bug fix #109
  .github/workflows/ci-pipeline.yml
  cypress/e2e/BottomNavBar.cy.js
  cypress/e2e/IndoorDirections.cy.js
  frontend/src/Components/BottomNavBar.tsx
Labels: bug, 🐛 Bug Fix

#112 chore: refactor project & deployment setup
  .github/workflows/build.yml
  Dockerfile
  backend/.env.example
  backend/package.json
  backend/src/app.ts
  backend/src/middlewares/sessionMiddleware.ts
  backend/src/tests/app.test.ts
  frontend/.env.example
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/Components/DirectionsViewMap.tsx
  frontend/src/Components/SearchBar.tsx
  frontend/src/api/mapsApi.ts
  frontend/src/components/Auth/LoginForm.css
  frontend/src/components/Auth/LoginForm.tsx
  frontend/src/components/Auth/RegisterForm.tsx
  frontend/src/components/BottomNavBar.tsx
  frontend/src/components/CalendarSelector.tsx
  frontend/src/components/DirectionsViewMap.tsx
  frontend/src/components/ErrorMessage.tsx
  frontend/src/components/EventDetailsModal.tsx
  frontend/src/components/GoogleCalendarConnect.tsx
  frontend/src/components/IndoorDirections/AccessibleToggle.tsx
  frontend/src/components/IndoorDirections/BuildingSelector.tsx
  frontend/src/components/IndoorDirections/CameraEvents.tsx
  frontend/src/components/IndoorDirections/ClickNavigation.tsx
  frontend/src/components/IndoorDirections/FloorSelector.tsx
  frontend/src/components/IndoorDirections/IndoorPOI.tsx
  frontend/src/components/IndoorDirections/Labels.tsx
  frontend/src/components/IndoorDirections/SearchNavigation.tsx
  frontend/src/components/LocationContext.tsx
  frontend/src/components/MapComponent.tsx
  frontend/src/components/Modal.tsx
  frontend/src/components/NavBar.tsx
  frontend/src/components/SearchBar.tsx
  frontend/src/components/ToggleCampusComponent.tsx
  frontend/src/components/UserLocation.tsx
  frontend/src/components/WeekView.tsx
  frontend/src/pages/Auth/LoginPage.tsx
  frontend/src/pages/Auth/RegisterPage.tsx
  frontend/src/pages/CalendarPage.tsx
  frontend/src/pages/Campus.tsx
  frontend/src/pages/Directions.tsx
  frontend/src/pages/IndoorDirections.tsx
  frontend/src/pages/WelcomePage.tsx
  frontend/src/routes.tsx
  frontend/src/services/PlaceServices.ts
  frontend/src/test/utils/CheckIfUserInBuilding.test.tsx
Labels: CI/CD, refactoring

#113 Feature/use current location startpoint
  .github/workflows/build.yml
  backend/src/routes/mapRoutes.ts
  backend/src/services/maps_services/locationServices.ts
  backend/src/tests/routes/mapRoutes.test.ts
  backend/src/tests/services/locationServices.test.ts
  cypress/e2e/Directions.cy.js
  cypress/e2e/GoogleCalendarComponents.cy.js
  frontend/src/api/mapsApi.ts
  frontend/src/components/LocationContext.tsx
  frontend/src/components/UserLocation.tsx
  frontend/src/pages/Directions.tsx
Labels: enhancement

#115 Add clarity to the website
  .github/workflows/ci-pipeline.yml
  Dockerfile
  cypress/e2e/GoogleCalendarComponents.cy.js
  frontend/index.html
Labels: usability-testing

#116 Feature/modes of transportation
  backend/response.json
  backend/src/routes/mapRoutes.ts
  backend/src/services/maps_services/directionsService.ts
  backend/src/tests/routes/mapRoutes.test.ts
  backend/src/tests/services/directionsService.test.ts
  backend/src/tests/services/placesServices.test.ts
  backend/src/tests/utils/orderRoutes.test.ts
  backend/src/utils/orderRoutes.ts
  cypress/e2e/Directions.cy.js
  cypress/fixtures/mockDirectionResponse.json
  frontend/src/api/mapsApi.ts
  frontend/src/components/BottomNavBar.tsx
  frontend/src/pages/Directions.tsx
  frontend/src/services/directionsServices.ts
Labels: enhancement, 🐛 Bug Fix

#119 [ADD] Feature/points of interest
  cypress/e2e/POIs.cy.js
  frontend/src/components/ModalPOI.css
  frontend/src/components/ModalPOI.tsx
  frontend/src/pages/Campus.tsx
  package-lock.json
  package.json
Labels: enhancement

#122 Feature/directions route display
  Dockerfile
  cypress/e2e/Directions.cy.js
  cypress/e2e/GoogleCalendarComponents.cy.js
  frontend/src/pages/Directions.tsx
Labels: enhancement

#158 [BUG FIX] directions displayed before selecting a route
  backend/src/services/maps_services/directionsService.ts
  backend/src/tests/routes/mapRoutes.test.ts
  backend/src/tests/services/directionsService.test.ts
  backend/src/tests/utils/trimRoutes.test.ts
  backend/src/utils/trimRoutes.ts
  frontend/src/components/RouteRenderer.tsx
  frontend/src/pages/Directions.tsx
Labels: refactoring, 🐛 Bug Fix

#159 Fix/building highlighting bug
  frontend/src/components/MapComponent.tsx
  frontend/src/components/UserLocation.tsx
  frontend/src/pages/Directions.tsx
Labels: bug, 🐛 Bug Fix

#160 [FIX] Fixed issue #107
  frontend/src/components/IndoorDirections/BuildingSelector.tsx
  frontend/src/pages/IndoorDirections.tsx
Labels: 🐛 Bug Fix

#164 Fix deployment issues
  Dockerfile
  backend/src/app.ts
  backend/src/middlewares/sessionMiddleware.ts
  frontend/src/pages/Directions.tsx
Labels: CI/CD, 🐛 Bug Fix

#165 Add Feature of Getting Directions Between Campuses
  cypress/e2e/Directions.cy.js
  frontend/src/pages/Directions.tsx
Labels: enhancement

#163 Enhance UI for Landing Page and Authentication Pages
  .github/workflows/build.yml
  cypress/e2e/BottomNavBar.cy.js
  cypress/e2e/Location.cy.js
  cypress/e2e/MapComponent.cy.js
  cypress/e2e/POIs.cy.js
  cypress/e2e/ToggleCampusComponent.cy.js
  frontend/components.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/Auth/LoginForm.css
  frontend/src/components/Auth/LoginForm.tsx
  frontend/src/components/Auth/RegisterForm.tsx
  frontend/src/components/BottomNavBar.tsx
  frontend/src/components/Landing/About.tsx
  frontend/src/components/Landing/Contact.tsx
  frontend/src/components/Landing/Feature-card.tsx
  frontend/src/components/Landing/LandingComponent.tsx
  frontend/src/components/Landing/NavBar.tsx
  frontend/src/components/Landing/Particule-background.tsx
  frontend/src/components/ui/button.tsx
  frontend/src/components/ui/input.tsx
  frontend/src/components/ui/sonner.tsx
  frontend/src/components/ui/textarea.tsx
  frontend/src/hooks/use-intersection-observer.ts
  frontend/src/hooks/use-media-query.ts
  frontend/src/icons/facebook-icon.tsx
  frontend/src/icons/github-icon.tsx
  frontend/src/icons/instagram-icon.tsx
  frontend/src/icons/logo.tsx
  frontend/src/icons/social-icon.tsx
  frontend/src/icons/x-icon.tsx
  frontend/src/index.css
  frontend/src/lib/utils.ts
  frontend/src/loaders/authLoader.ts
  frontend/src/pages/Auth/LoginPage.tsx
  frontend/src/pages/Auth/RegisterPage.tsx
  frontend/src/pages/Auth/RequestPasswordResetPage.tsx
  frontend/src/pages/Auth/ResetPasswordPage.tsx
  frontend/src/pages/Auth/VerifyEmailPage.tsx
  frontend/src/pages/WelcomePage.tsx
  frontend/src/routes.tsx
  frontend/tailwind.config.js
Labels: ui-improvement

#123 Implement directions to next class from the user's schedule
  backend/package-lock.json
  backend/package.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/EventDetailsModal.tsx
  frontend/src/components/IndoorDirections/SearchNavigation.tsx
  frontend/src/components/UserLocation.tsx
  frontend/src/pages/Directions.tsx
Labels: enhancement

#162 fixed display issue is dark mode
  frontend/src/components/Modal.tsx
  frontend/src/pages/Campus.tsx
  frontend/src/pages/Directions.tsx
Labels: 🐛 Bug Fix, usability-testing, ui-improvement

#170 Resolve error when choosing indoor directions
  frontend/package-lock.json
  frontend/src/components/IndoorDirections/SearchNavigation.tsx
Labels: bug, 🐛 Bug Fix

#169 implement access to shuttle schedule
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/ui/badge.tsx
  frontend/src/components/ui/card.tsx
  frontend/src/components/ui/progress.tsx
  frontend/src/components/ui/scroll-area.tsx
  frontend/src/components/ui/separator.tsx
  frontend/src/components/ui/tabs.tsx
  frontend/src/pages/Shuttle.tsx
  frontend/src/routes.tsx
Labels: enhancement

#174 Feature/access to current location of shuttle
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Shuttle/MapComponent.tsx
  frontend/src/components/Shuttle/MapController.tsx
  frontend/src/components/Shuttle/MapControls.tsx
  frontend/src/components/Shuttle/MapLegend.tsx
  frontend/src/components/Shuttle/NextDeparture.tsx
  frontend/src/components/Shuttle/RouteDialog.tsx
  frontend/src/components/Shuttle/ScheduleItem.tsx
  frontend/src/components/schedule-data.ts
  frontend/src/components/types.ts
  frontend/src/components/ui/dialog.tsx
  frontend/src/components/ui/dropdown-menu.tsx
  frontend/src/components/ui/label.tsx
  frontend/src/components/ui/switch.tsx
  frontend/src/components/ui/tooltip.tsx
  frontend/src/pages/Directions.tsx
  frontend/src/pages/Shuttle.tsx
  frontend/src/services/shuttle-service.ts
  frontend/src/test/utils/display-utils.test.ts
  frontend/src/test/utils/leaflet-utils.test.ts
  frontend/src/test/utils/time-utils.test.ts
  frontend/src/utils/display-utils.ts
  frontend/src/utils/leaflet-utils.ts
  frontend/src/utils/time-utils.ts
  frontend/vite.config.ts
Labels: enhancement

#175 Refactor backend cleanup
  backend/src/controllers/authController.ts
  backend/src/repositories/emailVerificationRepository.ts
  backend/src/repositories/passwordResetRepository.ts
  backend/src/repositories/sessionRepository.ts
  backend/src/repositories/userRepository.ts
  backend/src/routes/mapRoutes.ts
  backend/src/server.mts
  backend/src/services/EmailVerificationService.ts
  backend/src/services/authService.ts
  backend/src/services/emailService.ts
  backend/src/utils/orderRoutes.ts
Labels: refactoring

#176 Refactor IndoorDirections Floor Selector logic
  frontend/src/components/IndoorDirections/FloorSelector.tsx
Labels: refactoring
